import type { Applicant } from "./types";

const BATCH_SIZE = 100;

function idOf(n: number): string {
  return `A-${String(n).padStart(4, "0")}`;
}

type ApplicantDraft = Omit<
  Applicant,
  "application_status" | "deadline" | "competing_offer" | "scholarship" | "officer_notes" | "tags"
> &
  Partial<Pick<Applicant, "application_status" | "deadline" | "competing_offer" | "scholarship" | "officer_notes" | "tags">>;

function base(partial: ApplicantDraft): Applicant {
  const {
    application_status = "active",
    deadline = null,
    competing_offer = null,
    scholarship = null,
    officer_notes = null,
    tags = [],
    ...rest
  } = partial;
  return { application_status, deadline, competing_offer, scholarship, officer_notes, tags, ...rest };
}

/** Hand-authored cases that exercise each judgment and queue reason. */
const PLANTED: Applicant[] = [
  base({
    id: idOf(1),
    name: "Wei Chen",
    grade: "Year 9",
    age: 13,
    language: "Mandarin",
    second_language: "English",
    prior_school: "Dulwich College Beijing",
    prior_school_country: "CN",
    extracurricular: "piano since age 6, school orchestra, grade 7 exam",
    reason_for_applying: "We are relocating to London and want an IB continuum school.",
    siblings_information: "older brother, Year 12",
    tags: [
      "sample",
      "eal_english_medium_beijing",
      "extracurricular_sustained",
      "school_recognized",
      "sibling_current",
    ],
  }),
  base({
    id: idOf(2),
    name: "Nora Blake",
    grade: "Year 9",
    age: 13,
    language: "English",
    second_language: "French",
    prior_school: "Sevenoaks School",
    prior_school_country: "GB",
    extracurricular: "piano, swimming, chess",
    reason_for_applying: "A good school with a strong reputation near where we will live.",
    siblings_information: null,
    tags: ["extracurricular_bare", "school_recognized"],
  }),
  base({
    id: idOf(3),
    name: "Tomás Alvarez",
    grade: "Year 7",
    age: 11,
    language: "Spanish",
    second_language: "English",
    prior_school: "Dulwitch College",
    prior_school_country: "GB",
    extracurricular: "football captain for two seasons, regional U12 squad",
    reason_for_applying: "We visited the Year 7 open morning and liked the pastoral house system.",
    siblings_information: "none",
    tags: ["school_misspelled"],
  }),
  base({
    id: idOf(4),
    name: "Mei Lin",
    grade: "Year 9",
    age: 14,
    language: "Mandarin",
    second_language: null,
    prior_school: "a school in Beijing",
    prior_school_country: "CN",
    extracurricular: "art club",
    reason_for_applying: "Moving to the UK for work. Need a good international school.",
    siblings_information: null,
    tags: ["school_vague", "eal_high_need"],
  }),
  base({
    id: idOf(5),
    name: "Hao Zhang",
    grade: "Year 11",
    age: 15,
    language: "Mandarin",
    second_language: "English",
    prior_school: "北京市第四中学",
    prior_school_country: "CN",
    extracurricular: "school science Olympiad, bronze at city level",
    reason_for_applying: "Seeking an IB Diploma programme after a Chinese senior-middle pathway.",
    siblings_information: "cousin in Year 9 at another London school",
    tags: ["school_local_language", "age_ordinary"],
  }),
  base({
    id: idOf(6),
    name: "Priya Nair",
    grade: "Year 9",
    age: 13,
    language: "English",
    second_language: "Hindi",
    prior_school: "Green Valley Academy",
    prior_school_country: "IN",
    extracurricular: "debate since Year 6, state finalist last year",
    reason_for_applying: "Family transfer to London. Interested in your MUN and drama offering.",
    siblings_information: null,
    tags: ["school_unknown"],
  }),
  base({
    id: idOf(7),
    name: "Jonas Eriksson",
    grade: "Year 7",
    age: 12,
    language: "Swedish",
    second_language: "English",
    prior_school: "UWC Atlantic",
    prior_school_country: "GB",
    extracurricular: "sailing team, coastal rescue cadets for three years",
    reason_for_applying:
      "We chose Faria for the IB continuum after Atlantic and the weekly boarding option for Year 7.",
    siblings_information: "younger sister will apply next cycle",
    tags: ["school_recognized"],
  }),
  base({
    id: idOf(8),
    name: "Olivia Grant",
    grade: "Year 9",
    age: 13,
    language: "English",
    second_language: "Spanish",
    prior_school: "King's College School Wimbledon",
    prior_school_country: "GB",
    extracurricular: "netball, piano, volunteering",
    reason_for_applying:
      "We are looking for a nurturing yet academically rigorous environment that values the whole child, encourages curiosity, builds character, and prepares students for an uncertain future in a rapidly changing world. Excellence, kindness, and opportunity matter to our family, as they would to any family seeking the very best. The right community will help our daughter thrive, grow in confidence, and become a compassionate global citizen. We believe education is a journey and we want a partner school that walks that journey with us, supporting wellbeing while maintaining high standards and a love of learning that will last a lifetime.",
    siblings_information: "no siblings",
    tags: ["reason_long_generic"],
  }),
  base({
    id: idOf(9),
    name: "Samira Haddad",
    grade: "Year 9",
    age: 14,
    language: "Arabic",
    second_language: "English",
    prior_school: "ACS Cobham",
    prior_school_country: "GB",
    extracurricular: "orchestra viola since Year 5",
    reason_for_applying: "Closer commute and we already know families in your Year 9 cohort.",
    siblings_information: "Alex — I think they were at this school a while ago?",
    tags: ["ambiguous_sibling", "attention_ambiguous"],
  }),
  base({
    id: idOf(10),
    name: "Lucía Romero",
    grade: "Year 7",
    age: 11,
    language: "Spanish",
    second_language: "English (fluent, Cambridge B2)",
    prior_school: "King's College Soto de Viñuelas",
    prior_school_country: "ES",
    extracurricular: "basketball club three years, camp counselor-in-training",
    reason_for_applying: "Relocating from Madrid; want to stay in a British-curriculum international setting.",
    siblings_information: null,
    tags: ["non_english_no_rejection", "eal_compensating_english"],
  }),
  base({
    id: idOf(11),
    name: "Amara Okoye",
    grade: "Year 11",
    age: 16,
    language: "English",
    second_language: "Igbo",
    prior_school: "Atlantic Hall",
    prior_school_country: "NG",
    extracurricular: "founded a coding club; national science fair gold",
    reason_for_applying: "Applying for the need-aware scholarship and the IB Diploma.",
    siblings_information: null,
    scholarship: "Need-aware scholarship application submitted",
    tags: ["scholarship_trap", "attention_exceptional"],
  }),
  base({
    id: idOf(12),
    name: "Harry Patel",
    grade: "Year 9",
    age: 13,
    language: "English",
    second_language: "Gujarati",
    prior_school: "St Paul's Juniors",
    prior_school_country: "GB",
    extracurricular: "cricket 1st XI, county pathway",
    reason_for_applying: "Moving from junior school; visited your science labs on the Year 9 tour.",
    siblings_information: "none",
    tags: ["age_ordinary"],
  }),
  base({
    id: idOf(13),
    name: "Yuna Park",
    grade: "Year 9",
    age: 12,
    language: "Korean",
    second_language: "English",
    prior_school: "Seoul Foreign School",
    prior_school_country: "KR",
    extracurricular: "violin grade 6, chamber group",
    reason_for_applying: "Father's posting to London; one year young for Year 9 after a March birthday.",
    siblings_information: null,
    tags: ["age_one_year_off"],
  }),
  base({
    id: idOf(14),
    name: "Leo Moreau",
    grade: "Year 11",
    age: 13,
    language: "French",
    second_language: "English",
    prior_school: "Lycée International de Saint-Germain-en-Laye",
    prior_school_country: "FR",
    extracurricular: "judo club",
    reason_for_applying: "Family wants IB Diploma immediately.",
    siblings_information: null,
    officer_notes: "Age is two years below the Year 11 band with no system explanation on file.",
    tags: ["age_two_years_off", "attention_concerning", "single_serious_concern"],
  }),
  base({
    id: idOf(15),
    name: "Ananya Rao",
    grade: "Year 11",
    age: 14,
    language: "English",
    second_language: "Tamil",
    prior_school: "The Doon School",
    prior_school_country: "IN",
    extracurricular: "editor of the school weekly; trekking society leader",
    reason_for_applying:
      "Completed Class 10 at 14 under the Indian year-skipping pathway and is applying to start IB Diploma.",
    siblings_information: "brother alumni, class of 2022",
    officer_notes: "Prior system explains the young age for Year 11.",
    tags: ["age_system_explained"],
  }),
  base({
    id: idOf(16),
    name: "Blank Prior",
    grade: "Year 9",
    age: 13,
    language: "English",
    second_language: null,
    prior_school: null,
    prior_school_country: null,
    extracurricular: "swimming",
    reason_for_applying: null,
    siblings_information: null,
    tags: ["attention_incomplete", "missing_fields"],
  }),
  base({
    id: idOf(17),
    name: "No Activities File",
    grade: "Year 7",
    age: 11,
    language: null,
    second_language: null,
    prior_school: "Southbank International School",
    prior_school_country: "GB",
    extracurricular: null,
    reason_for_applying: "We live nearby.",
    siblings_information: null,
    tags: ["attention_incomplete", "missing_fields"],
  }),
  base({
    id: idOf(18),
    name: "Mixed Signals",
    grade: "Year 9",
    age: 13,
    language: "English",
    second_language: "Mandarin",
    prior_school: "Wellington College International Shanghai",
    prior_school_country: "CN",
    extracurricular: "thin list: clubs",
    reason_for_applying:
      "Teacher references describe a standout mathematician; the written statement is two generic sentences.",
    siblings_information: "maybe a half-sibling in sixth form?",
    tags: ["attention_ambiguous"],
  }),
  base({
    id: idOf(19),
    name: "Unclear Weighing",
    grade: "Year 11",
    age: 16,
    language: "Portuguese",
    second_language: "English",
    prior_school: "St. Paul's School São Paulo",
    prior_school_country: "BR",
    extracurricular: "national orchestra, but the dates conflict with the school calendar on file",
    reason_for_applying: "IB Diploma. Also considering staying in São Paulo.",
    siblings_information: "sister 'Mari' — year group not given",
    tags: ["attention_ambiguous", "ambiguous_sibling"],
  }),
  base({
    id: idOf(20),
    name: "Deadline Dani",
    grade: "Year 7",
    age: 11,
    language: "English",
    second_language: null,
    prior_school: "local primary, name unclear",
    prior_school_country: "GB",
    extracurricular: "none listed beyond play",
    reason_for_applying: "Need a place this term.",
    siblings_information: null,
    deadline: "Offer decision needed within 5 days — current school leaving date is set.",
    tags: ["attention_time_critical", "weak_time_critical"],
  }),
  base({
    id: idOf(21),
    name: "Other Offer Omar",
    grade: "Year 9",
    age: 14,
    language: "English",
    second_language: "Arabic",
    prior_school: "Jumeirah College",
    prior_school_country: "AE",
    extracurricular: "football academy, nothing else written",
    reason_for_applying: "May accept another London day school if we are slow.",
    siblings_information: null,
    competing_offer: "Holding a 10-day offer from another London independent school",
    tags: ["attention_time_critical"],
  }),
  base({
    id: idOf(22),
    name: "Sibling Standout",
    grade: "Year 7",
    age: 11,
    language: "English",
    second_language: "French",
    prior_school: "Thomas's Battersea",
    prior_school_country: "GB",
    extracurricular: "head of junior choir; published a class poetry pamphlet",
    reason_for_applying: "Younger sibling of Maya Adeyemi, currently Year 10 at Faria, house Lark.",
    siblings_information: "Maya Adeyemi, Year 10, current student",
    tags: ["attention_exceptional", "sibling_current"],
  }),
  base({
    id: idOf(23),
    name: "Quiet Scholar",
    grade: "Year 11",
    age: 15,
    language: "English",
    second_language: "Latin",
    prior_school: "Westminster Under School",
    prior_school_country: "GB",
    extracurricular: "UKMT gold three years running; mentoring younger olympiad students",
    reason_for_applying: "Wants your further maths and the IB Diploma higher-level physics pairing.",
    siblings_information: "none",
    scholarship: "Academic scholarship candidate, not time-pressured",
    deadline: null,
    tags: ["attention_exceptional", "exceptional_not_urgent", "scholarship_trap"],
  }),
  base({
    id: idOf(24),
    name: "Year Eleven at Thirteen",
    grade: "Year 11",
    age: 13,
    language: "English",
    second_language: null,
    prior_school: "village comprehensive, unnamed",
    prior_school_country: "GB",
    extracurricular: "gaming",
    reason_for_applying: "Parents requested Year 11 despite age.",
    siblings_information: "none",
    tags: ["attention_concerning", "single_serious_concern", "age_two_years_off"],
  }),
  base({
    id: idOf(25),
    name: "Safeguarding Flag",
    grade: "Year 9",
    age: 14,
    language: "English",
    second_language: null,
    prior_school: "left previous school mid-year",
    prior_school_country: "GB",
    extracurricular: "none",
    reason_for_applying: "Need a fresh start after a difficult year.",
    siblings_information: null,
    officer_notes: "Reference alludes to a behaviour concern that needs a considered look, not a fast pass.",
    tags: ["attention_concerning"],
  }),
  base({
    id: idOf(26),
    name: "Standout Incomplete",
    grade: "Year 9",
    age: 13,
    language: "English",
    second_language: "German",
    prior_school: "International School of Geneva",
    prior_school_country: "CH",
    extracurricular: "youth orchestra principal second violin, Swiss junior concerto finalist",
    reason_for_applying: null,
    siblings_information: "sister currently in Year 11 at Faria",
    tags: ["mixed_exceptional_incomplete", "attention_exceptional", "attention_incomplete", "sibling_current"],
  }),
  base({
    id: idOf(27),
    name: "Exceptional No Rush",
    grade: "Year 7",
    age: 12,
    language: "English",
    second_language: "Japanese",
    prior_school: "Nishimachi International School",
    prior_school_country: "JP",
    extracurricular: "kendo 3rd kyu; bilingual student newspaper editor",
    reason_for_applying:
      "Family relocates next August. Specifically asked about your Japanese mother-tongue maintenance and Year 7 outdoor week.",
    siblings_information: null,
    deadline: null,
    competing_offer: null,
    tags: ["exceptional_not_urgent", "attention_exceptional"],
  }),
  base({
    id: idOf(28),
    name: "Weak But Urgent",
    grade: "Year 9",
    age: 15,
    language: "English",
    second_language: null,
    prior_school: "unspecified academy",
    prior_school_country: "GB",
    extracurricular: "n/a",
    reason_for_applying: "Anywhere with a place.",
    siblings_information: null,
    deadline: "Current school closes their roll in six days",
    competing_offer: null,
    tags: ["weak_time_critical", "attention_time_critical"],
  }),
  base({
    id: idOf(29),
    name: "Trivial Gaps",
    grade: "Year 9",
    age: 13,
    language: "English",
    second_language: "French",
    prior_school: "City of London School for Girls",
    prior_school_country: "GB",
    extracurricular: null,
    reason_for_applying: "Sibling interest later; we liked the Year 9 curriculum booklet.",
    siblings_information: null,
    tags: ["trivial_missings"],
  }),
  base({
    id: idOf(30),
    name: "One Hard Problem",
    grade: "Year 11",
    age: 13,
    language: "English",
    second_language: "French",
    prior_school: "Eton College",
    prior_school_country: "GB",
    extracurricular: "rowed for two seasons, house prefect in Year 10 equivalent",
    reason_for_applying: "Wants your IB Diploma after a year in a British boarding house.",
    siblings_information: "no siblings at this school",
    officer_notes: "Everything is complete. The only issue is a two-year age gap for Year 11 with no system note.",
    tags: ["single_serious_concern", "attention_concerning", "age_two_years_off"],
  }),
  base({
    id: idOf(31),
    name: "Year Eight Ghost",
    grade: "Year 8",
    age: 12,
    language: "English",
    second_language: "Spanish",
    prior_school: "American School in London",
    prior_school_country: "GB",
    extracurricular: "drama lead in the middle-school play",
    reason_for_applying: "ASL family moving closer to your campus.",
    siblings_information: null,
    tags: ["unconfigured_grade"],
  }),
  base({
    id: idOf(32),
    name: "English in Nairobi",
    grade: "Year 9",
    age: 13,
    language: "English",
    second_language: "Swahili",
    prior_school: "Brookhouse School",
    prior_school_country: "KE",
    extracurricular: "hockey 1st team, service prefect",
    reason_for_applying: "Returning to the UK; wants to continue a British international pathway.",
    siblings_information: null,
    tags: ["english_in_non_english_country"],
  }),
  base({
    id: idOf(33),
    name: "High Need EAL",
    grade: "Year 7",
    age: 12,
    language: "Japanese",
    second_language: null,
    prior_school: "local municipal junior high",
    prior_school_country: "JP",
    extracurricular: "kendo club",
    reason_for_applying: "Father's work visa. Limited English at home.",
    siblings_information: null,
    tags: ["eal_high_need", "non_english_no_rejection"],
  }),
  base({
    id: idOf(34),
    name: "Waitlist Movement",
    grade: "Year 9",
    age: 14,
    language: "English",
    second_language: "Italian",
    prior_school: "Marymount International School",
    prior_school_country: "GB",
    extracurricular: "rowing novice, two terms",
    reason_for_applying: "On our waitlist since March; a Year 9 place just opened.",
    siblings_information: null,
    officer_notes: "Waitlist movement this week — delay may lose the family to another offer.",
    application_status: "waitlist",
    tags: ["attention_time_critical"],
  }),
  base({
    id: idOf(35),
    name: "Incomplete Pack Two",
    grade: "Year 11",
    age: 16,
    language: "French",
    second_language: "English",
    prior_school: null,
    prior_school_country: "FR",
    extracurricular: "theatre",
    reason_for_applying: "",
    siblings_information: "brother somewhere in sixth form, school not named",
    tags: ["attention_incomplete"],
  }),
  base({
    id: idOf(36),
    name: "Routine Complete",
    grade: "Year 7",
    age: 11,
    language: "English",
    second_language: "Latin",
    prior_school: "Bute House Preparatory",
    prior_school_country: "GB",
    extracurricular: "netball B team, recorder ensemble for two years",
    reason_for_applying: "Natural next school after prep; attended your Year 7 taster day.",
    siblings_information: "none",
    tags: ["routine"],
  }),
];

const FIRST = [
  "Aisha",
  "Ben",
  "Cara",
  "Diego",
  "Elena",
  "Farid",
  "Greta",
  "Hassan",
  "Ines",
  "Jules",
  "Keiko",
  "Liam",
  "Marta",
  "Nabil",
  "Olga",
  "Pavel",
  "Quinn",
  "Rina",
  "Soren",
  "Talia",
];

const LAST = [
  "Berg",
  "Costa",
  "Dubois",
  "Ellis",
  "Fujimoto",
  "Garcia",
  "Hughes",
  "Ibrahim",
  "Jansen",
  "Khan",
  "Lopez",
  "Mbeki",
  "Nguyen",
  "Owusu",
  "Petrov",
  "Qureshi",
  "Rossi",
  "Singh",
  "Tanaka",
  "Vogel",
];

const ROUTINE_SCHOOLS: { name: string; country: string }[] = [
  { name: "Haileybury", country: "GB" },
  { name: "International School of London", country: "GB" },
  { name: "Tanglin Trust School", country: "SG" },
  { name: "British School of Brussels", country: "BE" },
  { name: "Frankfurt International School", country: "DE" },
  { name: "American School of The Hague", country: "NL" },
  { name: "United World College of South East Asia", country: "SG" },
  { name: "British International School of Chicago", country: "US" },
  { name: "St. George's British International School", country: "IT" },
  { name: "International College Spain", country: "ES" },
];

const ROUTINE_REASONS = [
  "We attended the open morning and liked the pastoral houses.",
  "Relocating for work and want a familiar international curriculum.",
  "Sibling of a former applicant; the campus visit confirmed the fit.",
  "Looking for an IB continuum after a British-curriculum junior school.",
];

const ROUTINE_ACTIVITIES = [
  "school choir for three years, Saturday football",
  "scouts since age 9, community garden volunteer",
  "tennis club twice a week, beginner orchestra",
  "coding club and weekend climbing wall",
];

const GRADES: { name: string; age: number }[] = [
  { name: "Year 7", age: 11 },
  { name: "Year 7", age: 12 },
  { name: "Year 9", age: 13 },
  { name: "Year 9", age: 14 },
  { name: "Year 11", age: 15 },
  { name: "Year 11", age: 16 },
];

function routineApplicant(index: number): Applicant {
  const n = index + 1;
  const grade = GRADES[index % GRADES.length];
  const school = ROUTINE_SCHOOLS[index % ROUTINE_SCHOOLS.length];
  const first = FIRST[index % FIRST.length];
  const last = LAST[(index * 3) % LAST.length];
  return base({
    id: idOf(n),
    name: `${first} ${last}`,
    grade: grade.name,
    age: grade.age,
    language: index % 7 === 0 ? "English" : index % 7 === 1 ? "French" : "English",
    second_language: index % 5 === 0 ? "Spanish" : index % 5 === 1 ? "Mandarin" : "French",
    prior_school: school.name,
    prior_school_country: school.country,
    extracurricular: ROUTINE_ACTIVITIES[index % ROUTINE_ACTIVITIES.length],
    reason_for_applying: ROUTINE_REASONS[index % ROUTINE_REASONS.length],
    siblings_information: index % 11 === 0 ? "none" : null,
    tags: ["routine"],
  });
}

function buildApplicants(): Applicant[] {
  const byId = new Map<string, Applicant>();
  for (const planted of PLANTED) byId.set(planted.id, planted);
  const all: Applicant[] = [];
  for (let i = 0; i < BATCH_SIZE; i += 1) {
    const id = idOf(i + 1);
    all.push(byId.get(id) ?? routineApplicant(i));
  }
  return all;
}

export const APPLICANTS: Applicant[] = buildApplicants();

export const APPLICANT_COUNT = APPLICANTS.length;

export function applicantById(id: string): Applicant | undefined {
  return APPLICANTS.find((row) => row.id === id);
}

export function applicantsWithTag(tag: string): Applicant[] {
  return APPLICANTS.filter((row) => row.tags.includes(tag));
}

export const REQUIRED_TAGS = [
  "attention_incomplete",
  "attention_ambiguous",
  "attention_time_critical",
  "attention_exceptional",
  "attention_concerning",
  "mixed_exceptional_incomplete",
  "exceptional_not_urgent",
  "weak_time_critical",
  "trivial_missings",
  "single_serious_concern",
  "ambiguous_sibling",
  "non_english_no_rejection",
  "scholarship_trap",
  "age_ordinary",
  "age_one_year_off",
  "age_two_years_off",
  "age_system_explained",
  "eal_english_medium_beijing",
  "extracurricular_bare",
  "extracurricular_sustained",
  "school_recognized",
  "school_misspelled",
  "school_local_language",
  "school_unknown",
  "school_vague",
  "reason_long_generic",
  "unconfigured_grade",
  "english_in_non_english_country",
  "eal_high_need",
  "routine",
] as const;
