import type { Applicant } from "./types";

const BATCH_SIZE = 100;

function idOf(n: number): string {
  return `A-${String(n).padStart(4, "0")}`;
}

type ApplicantDraft = Omit<
  Applicant,
  "application_status" | "deadline" | "competing_offer" | "scholarship" | "officer_notes" | "tags"
> &
  Partial<Pick<Applicant, "application_status" | "deadline" | "competing_offer" | "scholarship" | "officer_notes" | "tags">>;

function base(partial: ApplicantDraft): Applicant {
  const {
    application_status = "active",
    deadline = null,
    competing_offer = null,
    scholarship = null,
    officer_notes = null,
    tags = [],
    ...rest
  } = partial;
  return { application_status, deadline, competing_offer, scholarship, officer_notes, tags, ...rest };
}

/** 逐条对应英文 PLANTED：同 id、同 age、同 tags，只翻散文。 */
const PLANTED: Applicant[] = [
  base({
    id: idOf(1),
    name: "陈伟",
    grade: "九年级",
    age: 13,
    language: "中文",
    second_language: "英语",
    prior_school: "Dulwich College Beijing",
    prior_school_country: "CN",
    extracurricular: "六岁起学钢琴，校管弦乐团，已过七级",
    reason_for_applying: "我们要搬到伦敦，希望找一所 IB 一贯制学校。",
    siblings_information: "哥哥，十二年级",
    tags: [
      "sample",
      "eal_english_medium_beijing",
      "extracurricular_sustained",
      "school_recognized",
      "sibling_current",
    ],
  }),
  base({
    id: idOf(2),
    name: "诺拉·布莱克",
    grade: "九年级",
    age: 13,
    language: "英语",
    second_language: "法语",
    prior_school: "Sevenoaks School",
    prior_school_country: "GB",
    extracurricular: "钢琴、游泳、象棋",
    reason_for_applying: "一所口碑好的学校，离我们将要住的地方也近。",
    siblings_information: null,
    tags: ["extracurricular_bare", "school_recognized"],
  }),
  base({
    id: idOf(3),
    name: "托马斯·阿尔瓦雷斯",
    grade: "七年级",
    age: 11,
    language: "西班牙语",
    second_language: "英语",
    prior_school: "德威公学北亰校区",
    prior_school_country: "GB",
    extracurricular: "校足球队队长两个赛季，地区 U12 集训队",
    reason_for_applying: "我们参加了七年级的开放早晨，很喜欢这里的导师制宿舍体系。",
    siblings_information: "无",
    tags: ["school_misspelled"],
  }),
  base({
    id: idOf(4),
    name: "林梅",
    grade: "九年级",
    age: 14,
    language: "中文",
    second_language: null,
    prior_school: "北京的一所学校",
    prior_school_country: "CN",
    extracurricular: "美术社",
    reason_for_applying: "因工作搬到英国。需要一所好的国际学校。",
    siblings_information: null,
    tags: ["school_vague", "eal_high_need"],
  }),
  base({
    id: idOf(5),
    name: "张浩",
    grade: "十一年级",
    age: 15,
    language: "中文",
    second_language: "英语",
    prior_school: "北京市第四中学",
    prior_school_country: "CN",
    extracurricular: "校科学奥林匹克竞赛，市级铜奖",
    reason_for_applying: "在中国读完高中前段后，希望衔接 IB 文凭项目。",
    siblings_information: "表亲在伦敦另一所学校读九年级",
    tags: ["school_local_language", "age_ordinary"],
  }),
  base({
    id: idOf(6),
    name: "普里娅·奈尔",
    grade: "九年级",
    age: 13,
    language: "英语",
    second_language: "印地语",
    prior_school: "Green Valley Academy",
    prior_school_country: "IN",
    extracurricular: "六年级起参加辩论，去年进入州级决赛",
    reason_for_applying: "全家调动到伦敦。对贵校的模拟联合国和戏剧课程感兴趣。",
    siblings_information: null,
    tags: ["school_unknown"],
  }),
  base({
    id: idOf(7),
    name: "约纳斯·埃里克森",
    grade: "七年级",
    age: 12,
    language: "瑞典语",
    second_language: "英语",
    prior_school: "UWC Atlantic",
    prior_school_country: "GB",
    extracurricular: "帆船队，海岸救援少年队三年",
    reason_for_applying: "在 Atlantic 之后，我们选择法瑞亚是看中 IB 一贯制，以及七年级的每周寄宿选项。",
    siblings_information: "妹妹会在下一轮申请",
    tags: ["school_recognized"],
  }),
  base({
    id: idOf(8),
    name: "奥利维娅·格兰特",
    grade: "九年级",
    age: 13,
    language: "英语",
    second_language: "西班牙语",
    prior_school: "King's College School Wimbledon",
    prior_school_country: "GB",
    extracurricular: "无板篮球、钢琴、志愿服务",
    reason_for_applying:
      "我们希望找到一个既有温度又在学业上足够严格的环境，重视完整的孩子，鼓励好奇心，塑造品格，并让学生为这个快速变化、充满不确定的未来做好准备。卓越、善良与机会对我们家庭很重要，正如它们对任何一个想为孩子争取最好的家庭都很重要。合适的社群会帮助我们的女儿茁壮成长、建立自信，成为一个有同理心的世界公民。我们相信教育是一段旅程，我们希望有一所学校能与我们一同走完这段旅程，在维持高标准与终身学习热情的同时，也照顾好孩子的身心健康。",
    siblings_information: "没有兄弟姐妹",
    tags: ["reason_long_generic"],
  }),
  base({
    id: idOf(9),
    name: "萨米拉·哈达德",
    grade: "九年级",
    age: 14,
    language: "阿拉伯语",
    second_language: "英语",
    prior_school: "ACS Cobham",
    prior_school_country: "GB",
    extracurricular: "五年级起在管弦乐团拉中提琴",
    reason_for_applying: "通勤更近，而且我们已经认识贵校九年级的一些家庭。",
    siblings_information: "Alex——我记得他们以前好像在这所学校？",
    tags: ["ambiguous_sibling", "attention_ambiguous"],
  }),
  base({
    id: idOf(10),
    name: "露西娅·罗梅罗",
    grade: "七年级",
    age: 11,
    language: "西班牙语",
    second_language: "英语（流利，剑桥 B2）",
    prior_school: "King's College Soto de Viñuelas",
    prior_school_country: "ES",
    extracurricular: "篮球俱乐部三年，夏令营辅导员储备生",
    reason_for_applying: "从马德里搬来；希望继续留在英式课程的国际学校环境里。",
    siblings_information: null,
    tags: ["non_english_no_rejection", "eal_compensating_english"],
  }),
  base({
    id: idOf(11),
    name: "阿玛拉·奥科耶",
    grade: "十一年级",
    age: 16,
    language: "英语",
    second_language: "伊博语",
    prior_school: "Atlantic Hall",
    prior_school_country: "NG",
    extracurricular: "创办了编程社团；全国科学展金奖",
    reason_for_applying: "申请需求知晓型奖学金以及 IB 文凭项目。",
    siblings_information: null,
    scholarship: "已提交需求知晓型奖学金申请",
    tags: ["scholarship_trap", "attention_exceptional"],
  }),
  base({
    id: idOf(12),
    name: "哈里·帕特尔",
    grade: "九年级",
    age: 13,
    language: "英语",
    second_language: "古吉拉特语",
    prior_school: "St Paul's Juniors",
    prior_school_country: "GB",
    extracurricular: "板球校队，郡级培养梯队",
    reason_for_applying: "从初级学校升学；参加九年级参观时看过贵校的科学实验室。",
    siblings_information: "无",
    tags: ["age_ordinary"],
  }),
  base({
    id: idOf(13),
    name: "朴允娜",
    grade: "九年级",
    age: 12,
    language: "韩语",
    second_language: "英语",
    prior_school: "Seoul Foreign School",
    prior_school_country: "KR",
    extracurricular: "小提琴六级，室内乐小组",
    reason_for_applying: "父亲派驻伦敦；三月出生，读九年级比同届小一岁。",
    siblings_information: null,
    tags: ["age_one_year_off"],
  }),
  base({
    id: idOf(14),
    name: "里奥·莫罗",
    grade: "十一年级",
    age: 13,
    language: "法语",
    second_language: "英语",
    prior_school: "Lycée International de Saint-Germain-en-Laye",
    prior_school_country: "FR",
    extracurricular: "柔道俱乐部",
    reason_for_applying: "家长希望立刻开始 IB 文凭项目。",
    siblings_information: null,
    officer_notes: "年龄比十一年级的年龄段低两岁，档案里没有任何学制方面的解释。",
    tags: ["age_two_years_off", "attention_concerning", "single_serious_concern"],
  }),
  base({
    id: idOf(15),
    name: "阿南雅·拉奥",
    grade: "十一年级",
    age: 14,
    language: "英语",
    second_language: "泰米尔语",
    prior_school: "The Doon School",
    prior_school_country: "IN",
    extracurricular: "校周报主编；徒步社负责人",
    reason_for_applying: "在印度的跳级路径下 14 岁读完十年级，现申请入读 IB 文凭项目。",
    siblings_information: "哥哥是校友，2022 届",
    officer_notes: "原学制可以解释他在十一年级的偏小年龄。",
    tags: ["age_system_explained"],
  }),
  base({
    id: idOf(16),
    name: "原校空白",
    grade: "九年级",
    age: 13,
    language: "英语",
    second_language: null,
    prior_school: null,
    prior_school_country: null,
    extracurricular: "游泳",
    reason_for_applying: null,
    siblings_information: null,
    tags: ["attention_incomplete", "missing_fields"],
  }),
  base({
    id: idOf(17),
    name: "活动空白",
    grade: "七年级",
    age: 11,
    language: null,
    second_language: null,
    prior_school: "Southbank International School",
    prior_school_country: "GB",
    extracurricular: null,
    reason_for_applying: "我们就住在附近。",
    siblings_information: null,
    tags: ["attention_incomplete", "missing_fields"],
  }),
  base({
    id: idOf(18),
    name: "信号矛盾",
    grade: "九年级",
    age: 13,
    language: "英语",
    second_language: "中文",
    prior_school: "Wellington College International Shanghai",
    prior_school_country: "CN",
    extracurricular: "列得很单薄：社团",
    reason_for_applying: "教师推荐信把他描述成极为突出的数学苗子；本人的书面陈述却只有两句套话。",
    siblings_information: "好像有个同父异母的哥哥在读高中部？",
    tags: ["attention_ambiguous"],
  }),
  base({
    id: idOf(19),
    name: "权衡不明",
    grade: "十一年级",
    age: 16,
    language: "葡萄牙语",
    second_language: "英语",
    prior_school: "St. Paul's School São Paulo",
    prior_school_country: "BR",
    extracurricular: "国家青年管弦乐团，但档案里的日期与校历冲突",
    reason_for_applying: "想读 IB 文凭项目。同时也在考虑留在圣保罗。",
    siblings_information: "姐姐「Mari」——没有写年级",
    tags: ["attention_ambiguous", "ambiguous_sibling"],
  }),
  base({
    id: idOf(20),
    name: "截止丹妮",
    grade: "七年级",
    age: 11,
    language: "英语",
    second_language: null,
    prior_school: "本地小学，校名不清",
    prior_school_country: "GB",
    extracurricular: "除了玩之外没有列出任何活动",
    reason_for_applying: "这学期就需要一个学位。",
    siblings_information: null,
    deadline: "5 天内需要给出录取答复——原学校的离校日期已经定了。",
    tags: ["attention_time_critical", "weak_time_critical"],
  }),
  base({
    id: idOf(21),
    name: "他校奥马",
    grade: "九年级",
    age: 14,
    language: "英语",
    second_language: "阿拉伯语",
    prior_school: "Jumeirah College",
    prior_school_country: "AE",
    extracurricular: "足球青训，其余没有写",
    reason_for_applying: "如果贵校太慢，我们可能会接受伦敦另一所走读学校。",
    siblings_information: null,
    competing_offer: "手上有伦敦另一所独立学校 10 天有效期的 offer",
    tags: ["attention_time_critical"],
  }),
  base({
    id: idOf(22),
    name: "手足优等",
    grade: "七年级",
    age: 11,
    language: "英语",
    second_language: "法语",
    prior_school: "Thomas's Battersea",
    prior_school_country: "GB",
    extracurricular: "初级合唱团团长；出过一本班级诗集",
    reason_for_applying: "是 Maya Adeyemi 的弟弟，她目前在法瑞亚读十年级，Lark 学院。",
    siblings_information: "Maya Adeyemi，十年级，在读学生",
    tags: ["attention_exceptional", "sibling_current"],
  }),
  base({
    id: idOf(23),
    name: "沉静学者",
    grade: "十一年级",
    age: 15,
    language: "英语",
    second_language: "拉丁语",
    prior_school: "Westminster Under School",
    prior_school_country: "GB",
    extracurricular: "连续三年拿到 UKMT 数学竞赛金奖；辅导低年级奥赛学生",
    reason_for_applying: "想读贵校的进阶数学，以及 IB 文凭项目的高级物理组合。",
    siblings_information: "无",
    scholarship: "学术奖学金候选人，没有时间压力",
    deadline: null,
    tags: ["attention_exceptional", "exceptional_not_urgent", "scholarship_trap"],
  }),
  base({
    id: idOf(24),
    name: "十三岁报十一年级",
    grade: "十一年级",
    age: 13,
    language: "英语",
    second_language: null,
    prior_school: "某乡村综合中学，未具名",
    prior_school_country: "GB",
    extracurricular: "打游戏",
    reason_for_applying: "家长不顾年龄，坚持要求读十一年级。",
    siblings_information: "无",
    tags: ["attention_concerning", "single_serious_concern", "age_two_years_off"],
  }),
  base({
    id: idOf(25),
    name: "保护标记",
    grade: "九年级",
    age: 14,
    language: "英语",
    second_language: null,
    prior_school: "学年中途从原学校离开",
    prior_school_country: "GB",
    extracurricular: "无",
    reason_for_applying: "经历了艰难的一年，需要一个新的开始。",
    siblings_information: null,
    officer_notes: "推荐信隐约提到一项行为方面的问题，需要认真看，而不是快速放行。",
    tags: ["attention_concerning"],
  }),
  base({
    id: idOf(26),
    name: "优秀但材料不全",
    grade: "九年级",
    age: 13,
    language: "英语",
    second_language: "德语",
    prior_school: "International School of Geneva",
    prior_school_country: "CH",
    extracurricular: "青年管弦乐团第二小提琴首席，瑞士青少年协奏曲比赛决赛选手",
    reason_for_applying: null,
    siblings_information: "姐姐目前在法瑞亚读十一年级",
    tags: ["mixed_exceptional_incomplete", "attention_exceptional", "attention_incomplete", "sibling_current"],
  }),
  base({
    id: idOf(27),
    name: "优秀不急",
    grade: "七年级",
    age: 12,
    language: "英语",
    second_language: "日语",
    prior_school: "Nishimachi International School",
    prior_school_country: "JP",
    extracurricular: "剑道三级；双语学生报主编",
    reason_for_applying: "全家明年八月搬迁。特意问了贵校的日语母语维持课程和七年级的户外周。",
    siblings_information: null,
    deadline: null,
    competing_offer: null,
    tags: ["exceptional_not_urgent", "attention_exceptional"],
  }),
  base({
    id: idOf(28),
    name: "偏弱但紧急",
    grade: "九年级",
    age: 15,
    language: "英语",
    second_language: null,
    prior_school: "某所未具名的学院",
    prior_school_country: "GB",
    extracurricular: "无",
    reason_for_applying: "哪里有学位就去哪里。",
    siblings_information: null,
    deadline: "原学校六天后就截止学籍名单",
    competing_offer: null,
    tags: ["weak_time_critical", "attention_time_critical"],
  }),
  base({
    id: idOf(29),
    name: "琐碎空缺",
    grade: "九年级",
    age: 13,
    language: "英语",
    second_language: "法语",
    prior_school: "City of London School for Girls",
    prior_school_country: "GB",
    extracurricular: null,
    reason_for_applying: "以后弟弟妹妹也有意向；我们很喜欢九年级的课程手册。",
    siblings_information: null,
    tags: ["trivial_missings"],
  }),
  base({
    id: idOf(30),
    name: "单点硬伤",
    grade: "十一年级",
    age: 13,
    language: "英语",
    second_language: "法语",
    prior_school: "Eton College",
    prior_school_country: "GB",
    extracurricular: "赛艇两个赛季，相当于十年级时担任学院长级学生",
    reason_for_applying: "在英式寄宿学院读了一年后，希望入读贵校的 IB 文凭项目。",
    siblings_information: "本校没有兄弟姐妹",
    officer_notes: "材料全部齐备。唯一的问题是十一年级存在两岁的年龄差，且没有学制说明。",
    tags: ["single_serious_concern", "attention_concerning", "age_two_years_off"],
  }),
  base({
    id: idOf(31),
    name: "八年级幽灵",
    grade: "八年级",
    age: 12,
    language: "英语",
    second_language: "西班牙语",
    prior_school: "American School in London",
    prior_school_country: "GB",
    extracurricular: "初中部话剧主演",
    reason_for_applying: "ASL 的家庭，想搬到离贵校校区更近的地方。",
    siblings_information: null,
    tags: ["unconfigured_grade"],
  }),
  base({
    id: idOf(32),
    name: "内罗毕的英语母语",
    grade: "九年级",
    age: 13,
    language: "英语",
    second_language: "斯瓦希里语",
    prior_school: "Brookhouse School",
    prior_school_country: "KE",
    extracurricular: "曲棍球校队，服务类长级学生",
    reason_for_applying: "回到英国；希望继续英式国际课程路径。",
    siblings_information: null,
    tags: ["english_in_non_english_country"],
  }),
  base({
    id: idOf(33),
    name: "英语支持需求高",
    grade: "七年级",
    age: 12,
    language: "日语",
    second_language: null,
    prior_school: "当地公立初中",
    prior_school_country: "JP",
    extracurricular: "剑道社",
    reason_for_applying: "父亲的工作签证。家里英语环境有限。",
    siblings_information: null,
    tags: ["eal_high_need", "non_english_no_rejection"],
  }),
  base({
    id: idOf(34),
    name: "候补变动",
    grade: "九年级",
    age: 14,
    language: "英语",
    second_language: "意大利语",
    prior_school: "Marymount International School",
    prior_school_country: "GB",
    extracurricular: "赛艇新手，两个学期",
    reason_for_applying: "从三月起就在贵校候补名单上；九年级刚好空出一个学位。",
    siblings_information: null,
    officer_notes: "本周候补名单有变动——拖延可能导致这个家庭被别的 offer 抢走。",
    application_status: "waitlist",
    tags: ["attention_time_critical"],
  }),
  base({
    id: idOf(35),
    name: "材料不全之二",
    grade: "十一年级",
    age: 16,
    language: "法语",
    second_language: "英语",
    prior_school: null,
    prior_school_country: "FR",
    extracurricular: "戏剧",
    reason_for_applying: "",
    siblings_information: "哥哥在读高中部，但没写是哪所学校",
    tags: ["attention_incomplete"],
  }),
  base({
    id: idOf(36),
    name: "常规完整",
    grade: "七年级",
    age: 11,
    language: "英语",
    second_language: "拉丁语",
    prior_school: "Bute House Preparatory",
    prior_school_country: "GB",
    extracurricular: "无板篮球 B 队，竖笛合奏两年",
    reason_for_applying: "读完预备学校后自然衔接的下一所学校；参加过贵校的七年级体验日。",
    siblings_information: "无",
    tags: ["routine"],
  }),
];

/** 名 —— 与英文 FIRST 等长（20），下标算术完全一致。 */
const FIRST = [
  "嘉怡",
  "柏宇",
  "思远",
  "一诺",
  "子涵",
  "若曦",
  "昊然",
  "梓萱",
  "雨桐",
  "承轩",
  "沐辰",
  "书瑶",
  "天佑",
  "静姝",
  "逸凡",
  "明轩",
  "悦心",
  "俊杰",
  "诗涵",
  "泽楷",
];

/** 姓 —— 与英文 LAST 等长（20）。 */
const LAST = [
  "陈",
  "林",
  "黄",
  "张",
  "李",
  "王",
  "吴",
  "刘",
  "郑",
  "谢",
  "徐",
  "孙",
  "马",
  "朱",
  "胡",
  "高",
  "罗",
  "梁",
  "宋",
  "唐",
];

/** 真实国际学校是专有名词，保留原名；国家码与英文完全一致。 */
const ROUTINE_SCHOOLS: { name: string; country: string }[] = [
  { name: "Haileybury", country: "GB" },
  { name: "International School of London", country: "GB" },
  { name: "Tanglin Trust School", country: "SG" },
  { name: "British School of Brussels", country: "BE" },
  { name: "Frankfurt International School", country: "DE" },
  { name: "American School of The Hague", country: "NL" },
  { name: "United World College of South East Asia", country: "SG" },
  { name: "British International School of Chicago", country: "US" },
  { name: "St. George's British International School", country: "IT" },
  { name: "International College Spain", country: "ES" },
];

const ROUTINE_REASONS = [
  "我们参加了开放早晨，喜欢这里的导师制宿舍。",
  "因工作调动搬迁，希望延续熟悉的国际课程。",
  "是此前一位申请人的兄弟姐妹；实地参观后确认很合适。",
  "读完英式课程的初级学校后，想找 IB 一贯制。",
];

const ROUTINE_ACTIVITIES = [
  "学校合唱团三年，周六踢足球",
  "九岁起参加童子军，社区花园志愿者",
  "每周两次网球俱乐部，管弦乐团初级班",
  "编程社团，周末攀岩馆",
];

/** 与英文 GRADES 同序同龄，只换年级名。 */
const GRADES: { name: string; age: number }[] = [
  { name: "七年级", age: 11 },
  { name: "七年级", age: 12 },
  { name: "九年级", age: 13 },
  { name: "九年级", age: 14 },
  { name: "十一年级", age: 15 },
  { name: "十一年级", age: 16 },
];

function routineApplicant(index: number): Applicant {
  const n = index + 1;
  const grade = GRADES[index % GRADES.length];
  const school = ROUTINE_SCHOOLS[index % ROUTINE_SCHOOLS.length];
  const first = FIRST[index % FIRST.length];
  const last = LAST[(index * 3) % LAST.length];
  return base({
    id: idOf(n),
    name: `${last}${first}`,
    grade: grade.name,
    age: grade.age,
    language: index % 7 === 0 ? "英语" : index % 7 === 1 ? "法语" : "英语",
    second_language: index % 5 === 0 ? "西班牙语" : index % 5 === 1 ? "中文" : "法语",
    prior_school: school.name,
    prior_school_country: school.country,
    extracurricular: ROUTINE_ACTIVITIES[index % ROUTINE_ACTIVITIES.length],
    reason_for_applying: ROUTINE_REASONS[index % ROUTINE_REASONS.length],
    siblings_information: index % 11 === 0 ? "无" : null,
    tags: ["routine"],
  });
}

function buildApplicants(): Applicant[] {
  const byId = new Map<string, Applicant>();
  for (const planted of PLANTED) byId.set(planted.id, planted);
  const all: Applicant[] = [];
  for (let i = 0; i < BATCH_SIZE; i += 1) {
    const id = idOf(i + 1);
    all.push(byId.get(id) ?? routineApplicant(i));
  }
  return all;
}

export const APPLICANTS_ZH: Applicant[] = buildApplicants();
